version: '3.3'

services:
  tomatobackend:
    build: ./backend/
    container_name: tomatobackend
    depends_on:
      - tomatodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tomatodb:5432/tomato
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FRONTEND_HOST=http://localhost
  tomatofrontend:
    container_name: tomatofrontend
    build: ./frontend/
    ports:
      - "80:80"
  tomatodb:
    image: 'postgres:13.1-alpine'
    container_name: tomatodb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tomato
    expose:
      - 5432
